# Generated by Django 3.2.7 on 2021-09-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('arbistore', '0001_initial'), ('arbistore', '0002_auto_20210920_0527'), ('arbistore', '0003_auto_20210920_0532'), ('arbistore', '0004_auto_20210920_0546'), ('arbistore', '0005_auto_20210920_0550'), ('arbistore', '0006_auto_20210920_0556'), ('arbistore', '0007_auto_20210920_0624'), ('arbistore', '0008_auto_20210921_0941'), ('arbistore', '0009_auto_20210921_0957'), ('arbistore', '0010_auto_20210922_0522'), ('arbistore', '0011_alter_subcategory_category'), ('arbistore', '0012_alter_user_full_name')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('White', 'White'), ('Green', 'Green')], max_length=20)),
                ('stock', models.IntegerField()),
                ('size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbistore.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/')),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbistore.productdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbistore.brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbistore.category')),
                ('sub_category', models.ManyToManyField(to='arbistore.SubCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arbistore.product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('full_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
