# Generated by Django 3.2.7 on 2021-10-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
