# Generated by Django 2.2.12 on 2021-09-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0002_auto_20210920_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
