# Generated by Django 2.2.12 on 2021-09-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0003_auto_20210920_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_catergory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_catergory',
            field=models.ManyToManyField(to='arbistore.SubCategory'),
        ),
    ]
