# Generated by Django 3.2.6 on 2021-10-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0003_auto_20211012_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
