# Generated by Django 2.2.12 on 2021-09-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0004_auto_20210920_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_catergory',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arbistore.SubCategory'),
        ),
    ]
