# Generated by Django 3.2.6 on 2021-10-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0005_alter_productsizestock_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizestock',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
