# Generated by Django 2.2.12 on 2021-09-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0005_auto_20210920_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(to='arbistore.SubCategory'),
        ),
    ]
