# Generated by Django 3.2.7 on 2021-09-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0008_auto_20210921_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_catergory',
            new_name='sub_category',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arbistore.productdetail'),
        ),
    ]
