# Generated by Django 3.2.7 on 2021-09-22 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0009_auto_20210921_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_detail_id',
            new_name='product_detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_detail',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arbistore.product'),
            preserve_default=False,
        ),
    ]
