# Generated by Django 3.2.7 on 2021-09-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0010_auto_20210922_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbistore.category'),
        ),
    ]
