# Generated by Django 3.2.7 on 2021-09-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbistore', '0011_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=300),
        ),
    ]
